name: Deploy on GCP VM lourenco

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H louren.co.in > ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
          head ~/.ssh/id_rsa
          ls -a ~/.ssh/
      - name: Deploy
        run: |
          ssh -T user@louren.co.in << EOF
            export PATH=/home/user/.nvm/versions/node/v23.11.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin
            pm2 stop analisador-csv-ga4-vs-floodlight
            cd ~/GitRepos/analisador-csv-ga4-vs-floodlight
            git pull
            npm install
            pm2 start analisador-csv-ga4-vs-floodlight
          EOF